site_name: "Nicolas Mendoza's Portfolio"
site_author: "Nicolas Mendoza"
site_description: "Portfolio showcasing behavioural science projects and research illustrative of my work."
theme:
  name: material

  palette:
    scheme: slate     # dark base
    primary: indigo
    accent: deep-purple

  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant          # client-side smooth scroll
    # - toc.integrate              # integrate TOC into page
    - content.code.annotate      # nice code blocks if needed
  highlightjs: true
  highlight_theme: 'ayu'  # try 'monokai', 'solarized-light', 'default', etc.
nav:
  - Home: index.md
  - Projects:
      - Message Framing for Physical Activity: projects/bachelor-thesis.md
      - Increasing Vegetable Consumption in Children: projects/masters-thesis.md
      - People Development Internship: projects/redcare-internship.md
      - Market Research Internship: projects/caracol-internship.md
  - About: about.md
  - Contact: contact.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sofiaheld24
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sofiaheldr/
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# site_url: "https://sofiaheldruiz.de"

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/arrows.js
  - js/particles.min.js   # particles.js library
  - js/stars.js           # your init code
  - https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap
  - https://unpkg.com/rellax@1.12.1/rellax.min.js
  - js/space-cursor.js


extra_css:
  - css/cards.css
  - css/timeline.css
  - css/overrides.css
  - css/space.css
  - css/space-cursor.css